config/routes.rb
Rails.application.routes.draw do

 namespace :admin do #admin/～を加える
  get 'signup', to: 'users#new' #user/newアクションのURLの最後はsignup

  resources :users, only: [:create]
  #get⇒users/index,show,new,edit (4つ)post⇒users/create (1つ)patch⇒users/update(1つ) put⇒users/update(１つ) delete⇒users/destroy(1つ)
 end  

  post 'cabinets', to: 'cabinets#create' #5.24追加
  post 'requests', to: 'requests#create' #5.24追加
  resources :requests #5.9追加 5.19変更

  root to: 'sessions#new' #root_to=最初の"/"でリンクする先を指定。
  
  get 'login', to: 'sessions#new' #session/newアクションのURLの最後はlogin
  post 'login', to: 'sessions#create' #session/createアクションのURLの最後はlogin
  delete 'logout', to: 'sessions#destroy' #session/destroyアクションのURLの最後はlogout
  

  delete :cabinets, to: 'cabinets#destroy_all' #5.6追加　一括削除
  patch 'update_delete', to: 'cabinets#update_delete' #6.6追加
  patch 'update_accept', to: 'cabinets#update_accept' #6.7追加
  patch 'update_cancel', to: 'cabinets#update_cancel' #6.13追加
  
  resources :cabinets  #, except: [:index]で除外可能
  #get⇒cabinets/index,show,new,edit (4つ)post⇒cabinets/create (1つ)patch⇒cabinets/update(1つ) put⇒cabinets/update(１つ) delete⇒cabinets/destroy(1つ)
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user #コンソールでRequest.user（インスタンスメソッド）が使えるようになる。Cabinet登録時にこれが悪さしてる！
  belongs_to :cabinet #requestはひとつのcabinetにつながっている コンソールでRequest.cabinet（インスタンスメソッド）が使えるようになる。Cabinet登録時にこれが悪さしてる！
  
  validates :file_no, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :file_name, presence: true, length: { maximum: 50 }, uniqueness: true
  #validates :expired_at, presence: true, numericality: { only_integer: true } #保管期限 numericality数値のみ、only_integerかつ整数のみ。
  validates :placed_at, presence: true, length: { maximum: 50 } #保管場所    
  validates :comment, length: { maximum: 255 }
  
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController #cabinetへの登録申請、承認等
  before_action :require_user_logged_in, only: [:index] #ApplicationControllerで定義したメソッド。ログインしていないユーザをログイン画面に強制的にとばす
  before_action :set_request, only: [:show, :edit, :update, :destroy] #特定のパラメータを取り出す。つまりアクションに選択するメソッドを追加・共通化する
  #before_action :correct_user, only: [:destroy] #before_action では only: で指定されたアクションに対して、事前処理を設定できます
  #before_action :set_current_user, only: [:create]
  
  def index
    @msg = 'Cabinet data.'
   #@cabinets = Cabinet.order(id: :asc).page(params[:page]).per(10)
    @requests = Cabinet.order(id: :asc).page(params[:page]).per(10).where.not(status: '登録済') #status=登録済以外を表示
  end

  def show
    @request = Cabinet.find(params[:id])
  end

  def new
    @request = Request.new #Cabinetの登録申請ボタン押下で実行するアクション
  end

  def create
    @request = Request.new(request_params)

    if @request.save
      
      flash[:success] = '登録申請を受け付けました。'
      redirect_to cabinets_url #redirect_toアクションはデータ保存後画面遷移
    else
      flash.now[:danger] = '登録申請に失敗しました。再度やり直してください。'
      render 'cabinets/new' #render :newだとrequests/new.html.erbを自動表示するので、別フォルダを指定したい場合に左記のように書く。
      #renderはsave実行後にViewを表示。一方redirectはsave実行後に別のコントローラのアクション(cabinet/index)を実行。アクションが１つか２つかの違い
    end
  end


  def edit
  end

  def update
    if @request.update(request_params)
      flash[:success] = 'Request は正常に更新されました'
      redirect_to @request
    else
      flash.now[:danger] = 'Request は更新されませんでした'
      render :edit
    end
  end

  def update_accept #承認ボタン
    @cabinet = Cabinet.find(params[:id])
    if @cabinet.update_attributes(status: "登録済")
      @cabinet.request.update(status: "登録済")
      flash[:success] = '書庫に正常に登録されました'
      redirect_to cabinets_url
    else
      flash.now[:danger] = '書庫の登録に失敗しました'
      render :edit
    end
  end


  def destroy
    @request.destroy #destroy前にfindしている

    flash[:success] = '申請を差し戻しました'
    redirect_to requests_path
    
  end
  
  def destroy_all
    checked_data = params[:deletes].keys # ここでcheckされたデータを受け取っています。
    if @cabinets.destroy(checked_data)
      flash[:success] = '削除申請を受け付けました。'
      redirect_to cabinets_url
    else
      flash.now[:danger] = '削除申請に失敗しました。再度やり直してください。'
      render :new #cabinets/new.html.erbを表示するのみ（newアクションは実行しない）
    end
  end
end  



  private
  def cabinet_params #セキュリティ対策。newメソッドのフォーム入力データをフィルタリングする。HTTPリク攻撃防止
    params.require(:cabinet).permit(:file_no, :file_name, :expired_at, :placed_at) 
    #Cabinetモデルを収集先に宣言。permit→その中で取得を許可する値。ユーザと管理者の取得情報の区別も可
  end

  def request_params #セキュリティ対策。newメソッドのフォーム入力データをフィルタリングする。HTTPリク攻撃防止
    params.require(:request).permit(:file_no, :file_name, :expired_at, :placed_at)  #Cabinet登録申請ボタンが機能する
    #Requestモデルを収集先に宣言。permit→その中で取得を許可する値。ユーザと管理者の取得情報の区別も可
  end
  
  def set_request
    @request = Cabinet.find(params[:id])
  end

app/views/requests/index.html.erb
<h1 class="display-3 text-primary">Request</h1>

<h3><%= @msg %></h3>


<%#= form_with @user, url: {controller: 'users', action: 'index' } do  |form| %>
<%#= form_with(model: @cabinet, url: cabinets_path,local: true) do |f| %>
<%#= form_with(model: @request, local: true) do |f| %> <%# form_with はデフォルトでcabinets_pathを認識、cabinet controllerのnew createに飛ぶことが決定 %>

  <table class="table table-striped table-bordered text-center "> <%# table class="table" 基本のテーブルが作成される＋α %>

    <tr class="table-primary ">
      <th>No.</th><th>ファイルNo.</th><th>ファイル名</th><th>保管期限</th><th>保管場所</th><th>起案者</th><th>起案日</th><th colspan="2">諾否</th>
    </tr>

    <% @requests.each do |cabinet| %> <%# 定義した@requestsからデータ取り出し。変数を|cabinet|と定義 %>
    <tr>
      <td><%= link_to cabinet.id, request_path(id: cabinet.id) %></td> <%# link_to 文字列, path名。この場合cabinet.idを押すとrequestのshowに移動する %>
      <td class="text-left"><%= cabinet.file_no %></td>
      <td class="text-left"><%= cabinet.file_name %></td>
      <td><%= cabinet.expired_at.strftime('%Y/%m/%d') %></td>
      <td><%= cabinet.placed_at %></td>
      <td><%= cabinet.user_id %></td>
      <td><%= cabinet.created_at.strftime('%Y/%m/%d') %></td>
      <td><%= link_to '差し戻し', cabinet, method: :delete, data: { confirm: '本当に差し戻してよろしいですか？' }, class: 'btn btn-danger btn-sm' %></td>
      <td><%= link_to '承　認', update_accept_path(id: cabinet.id), method: :patch, data: { confirm: '本当に承認してよろしいですか？' }, class: 'btn btn-primary btn-sm' %></td>
    </tr>
  
    <% end %>
  </table>

  <%#= form_with @cabinet, url: {controller: 'cabinets', action: 'create' } do  |form| %>
    <%#= form.text_field :name %>
    <%#= f.submit '承認', class: 'btn btn-primary ' %>
  <%# end %>


  <%# end %>


<%= paginate @requests %> <%# ページネイトができるようになる %>

app/views/requests/show.html.erb
<h1 class="display-5 text-dark">Cabinet(詳細)</h1>

<table class="table table-striped table table-bordered ">
  <tr>
    <th class="table-primary ">項目</th>
    <td class="table-primary ">内容</td>
  </tr>
  <tr>
    <th>登録No</th>
    <td><%= @request.id %></td>
  </tr>
  <tr>
    <th>ファイルＮｏ</th>
    <td><%= @request.file_no %></td>
  </tr>
  <tr>
    <th>ファイル名</th>
    <td><%= @request.file_name %></td>
  </tr>
  <tr>
    <th>保管期限</th>
    <td><%= @request.expired_at.strftime('%Y/%m/%d') %></td>
  </tr>
  <tr>
    <th>保管場所</th>
    <td><%= @request.placed_at %></td>
  </tr>
    <tr>
    <th>ステータス</th>
    <td><%= @request.status %></td>
  </tr>
  <tr>
    <th>起案者</th>
    <td><%= @request.user_id %></td>
  </tr>
  <tr>
    <th>起案日</th>
    <td><%= @request.created_at.strftime('%Y/%m/%d') %></td>
  </tr>

</table>

<%= link_to '一覧に戻る', requests_path, class: 'btn btn-light'  %>

<%= link_to '承　　 認', update_accept_path(id: @request.id), method: :patch, data: { confirm: '本当に承認してよろしいですか？' }, class: 'btn btn-primary' %>
<%# @request.id⇒requests controllerに定義しているものが@requestのみのため %>

<%= link_to '差し戻し', @request, method: :delete, data: { confirm: '本当に差し戻してよろしいですか？' }, class: 'btn btn-danger' %>