config/routes.rb
Rails.application.routes.draw do

 namespace :admin do #admin/～を加える
  get 'signup', to: 'users#new' #user/newアクションのURLの最後はsignup

  resources :users, only: [:create]
  #get⇒users/index,show,new,edit (4つ)post⇒users/create (1つ)patch⇒users/update(1つ) put⇒users/update(１つ) delete⇒users/destroy(1つ)
 end  

  post 'cabinets', to: 'cabinets#create' #5.24追加
  post 'requests', to: 'requests#create' #5.24追加
  resources :requests #5.9追加 5.19変更

  root to: 'sessions#new' #root_to=最初の"/"でリンクする先を指定。
  
  get 'login', to: 'sessions#new' #session/newアクションのURLの最後はlogin
  post 'login', to: 'sessions#create' #session/createアクションのURLの最後はlogin
  delete 'logout', to: 'sessions#destroy' #session/destroyアクションのURLの最後はlogout
  

  delete :cabinets, to: 'cabinets#destroy_all' #5.6追加　一括削除
  patch 'update_delete', to: 'cabinets#update_delete' #6.6追加
  patch 'update_accept', to: 'cabinets#update_accept' #6.7追加
  patch 'update_cancel', to: 'cabinets#update_cancel' #6.13追加
  
  resources :cabinets  #, except: [:index]で除外可能
  #get⇒cabinets/index,show,new,edit (4つ)post⇒cabinets/create (1つ)patch⇒cabinets/update(1つ) put⇒cabinets/update(１つ) delete⇒cabinets/destroy(1つ)
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! } 
  #文字をすべて小文字に変換する
  validates :name, presence: true, length: { maximum: 50 }, uniqueness: true
  #空文字を許さず長さ50文字まで。重複を許さない
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    #正しいメアド形式かを判断
                    uniqueness: { case_sensitive: false }
                    #重複を許さず大文字小文字を区別しない
                    
                    
  has_secure_password
  #パスワードの暗号化
  #入力文字を保存させない
  #ログイン認証メソッドauthenticate？を提供
  
  has_many :cabinets #ユーザは複数のcabinet(書庫登録データ)とつながっている コンソールでUser.cabinets（インスタンスメソッド）が使えるようになる
  has_many :requests #ユーザは複数のrequest(申請)とつながっている 5.10追加 User.requests（インスタンスメソッド）が使えるようになる
  has_many :trackings #ユーザは複数のtracking(操作履歴)とつながっている User.trackings（インスタンスメソッド）が使えるようになる
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController #Admin・・・管理機能専用のコントローラ。将来管理系の機能を追加することを想定して新たに作成
  def index
    #@users = User.all
  end
  
  def show
   @user = User.find(user_params)
  end
  
  def new
    @user = User.new
  end

  def edit
    @user = User.find(user_params)
  end
  
  def create
    @user = User.new(user_params) #下部のprivateで定義しないと使えない！
    
    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to admin_signup_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new #users/new.html.erbを表示するのみ（newアクションは実行しない）
    end
  end

  def update
    @user = User.find(params[:id])
  
    if @user.update(user_params)
      redirect_to admin_users_url(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  def user_params #ユーザIDメソッド
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation) #adminを追記
    #Userモデルを収集先に宣言。permit→その中で取得を許可する値。ユーザと管理者の取得情報の区別も可
  end
  
  def require_admin #管理者以外禁止メソッド
    redirect_to root_url unless current_user.admin #管理者以外がURL直入力でtryしたときはログイン画面へ飛ばす
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController #admin専用を作ったので不要　あとで削除

  def index
    #@users = User.order(id: :desc).page(params[:page]).per(25) #Userはモデル。order(id)でid情報取得
  end     #id降順にユーザ一覧取得  ページネーション(分割)適用 1pにつき25件まで取得

  def show #そのユーザid専用のページへ飛ばす。
  end

  def new
    @user = User.new #signupクリック時に実行するアクション。rails標準装備。Userモデルに.newアクションで情報生成。保存(.save)は別途必要。コンソールではUser.new（name:"tanaka" , email: "tech@gmail.com"）と入力
  end

  def create 
    @user = User.new(user_params) #@がつけばインスタンス変数、クラスを元にしたオブジェクトの中で常に値を保持している変数のこと

    if @user.save #user新規登録後保存。@をつけないとuserがviewに反映されない
      flash[:success] = 'ユーザを登録しました。'
      redirect_to cabinets_index_url #redirect_toは転送メソッド、action: :アクション名で実行。ちなみにredirect_to @user・・・get "/users/:id" => "users#show"の事。users showアクションへ強制移動、show.html.erbを呼ぶ。
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new #users/new.html.erbを表示するのみ（newアクションは実行しない）
    end
    
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

  private

  def user_params #new.html.erbでform_for or withを利用する際は、二重ハッシュ（モデル名とバリュー）で情報が飛ばされます。そのため、コントローラー上、requireでモデル指定・permitでバリュー指定が必要になります。
    params.require(:user).permit(:name, :email, :password, :password_confirmation) 
    #Userモデルを収集先に宣言。permit→その中で取得を許可する値。ユーザと管理者の取得情報の区別も可
  end

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<h1>Admin::Users#index</h1>
<p>Find me in app/views/admin/users/index.html.erb</p>

app/views/admin/users/new.html.erb
<div class="text-center"> <%# bootstrap適用 %>
  <h1>Sign up</h1>　 <%# 新規登録画面のタイトル %>
</div>

<div class="row mb-5">
  <div class="col-sm-6 offset-sm-3"> <%# ３カラム空白＋６カラム使用、残り３カラム空き %>
 <%#= form_with model: @user, url: users_path,local: true do |form| %> 
    <%= form_with(model: @user, url: admin_users_path,local: true) do |f| %> <%# local: true⇒画面遷移可能 、form_with はデフォルトでusers_pathを認識、URLを指定しないと希望先へ飛ばない。 %>
      <%# form_with(model: @user)⇒Controllerのnew アクションで用意した@userを使用することを明示 %>
      <%= render 'layouts/error_messages', model: f.object %> <%# renderは画面遷移のみ %>
      <%# render 'フォルダ名/ファイル名'  エラーメッセージファイルを引っ張ってくる。なぜ引っ張る工程を踏むのか、それは別Viewでも同じコードを使用するため長文入力よりrenderの方が効率が良い%>
      <div class="form-group"> <%# bootstrap適用 %>
        <%= f.label :name, '氏　名' %> <%# ラベル名をNameに %>
        <%= f.text_field :name, class: 'form-control', placeholder: "ex.山田太郎" %> <%# form-controlがないとレイアウト崩れが起きる %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email, class: 'form-control', placeholder: "ex.taro@gmail.com" %>
      </div>
      
      <div class="form-group">
        <%= f.check_box :admin, id: "check1" %> <%# radio_button %>
        <%= f.label :admin, '管理者権限' %> <%# adminのカラムを宣言したことで、登録される %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'パスワード' %>
        <%= f.password_field :password, class: 'form-control', placeholder: "ex.567252taro" %> <%# 'form-control'でフォーム幅と名札を２段にする %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'パスワード（確認）' %>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "ex.567252taro" %>
      </div>
      


      <%= f.submit '新規登録', class: 'btn btn-primary ' %> <%# f.submit⇒対応するモデルクラスが何も情報を持っていなければ自動的にcreateアクションへ、すでに情報を持っている場合はupdateアクションへ自動的に振り分けてくれる %>
      <%# btn-block 幅いっぱい広がる %>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>
<p>Find me in app/views/admin/users/show.html.erb</p>