config/routes.rb
Rails.application.routes.draw do

 namespace :admin do #admin/～を加える
  get 'signup', to: 'users#new' #user/newアクションのURLの最後はsignup

  resources :users, only: [:create]
  #get⇒users/index,show,new,edit (4つ)post⇒users/create (1つ)patch⇒users/update(1つ) put⇒users/update(１つ) delete⇒users/destroy(1つ)
 end  

  post 'cabinets', to: 'cabinets#create' #5.24追加
  post 'requests', to: 'requests#create' #5.24追加
  resources :requests #5.9追加 5.19変更

  root to: 'sessions#new' #root_to=最初の"/"でリンクする先を指定。
  
  get 'login', to: 'sessions#new' #session/newアクションのURLの最後はlogin
  post 'login', to: 'sessions#create' #session/createアクションのURLの最後はlogin
  delete 'logout', to: 'sessions#destroy' #session/destroyアクションのURLの最後はlogout
  

  delete :cabinets, to: 'cabinets#destroy_all' #5.6追加　一括削除
  patch 'update_delete', to: 'cabinets#update_delete' #6.6追加
  patch 'update_accept', to: 'cabinets#update_accept' #6.7追加
  patch 'update_cancel', to: 'cabinets#update_cancel' #6.13追加
  
  resources :cabinets  #, except: [:index]で除外可能
  #get⇒cabinets/index,show,new,edit (4つ)post⇒cabinets/create (1つ)patch⇒cabinets/update(1つ) put⇒cabinets/update(１つ) delete⇒cabinets/destroy(1つ)
end

app/models/cabinet.rb
class Cabinet < ApplicationRecord
  belongs_to :user #各cabinetは一人のユーザに紐つく。多対１。adminは不可 Cabinet.user（インスタンスメソッド）が使えるようになる
  has_one :request, dependent: :destroy #cabinetはrequestを持つ親。かつ１対１
  
  #ユーザの紐付け無しには cabinet を保存・編集できません。
  validates :file_no, presence: true, length: { maximum: 50 }, uniqueness: true
  validates :file_name, presence: true, length: { maximum: 50 }, uniqueness: true
  #validates :expired_at, presence: true, numericality: { only_integer: true } #保管期限
  validates :placed_at, presence: true, length: { maximum: 50 } #保管場所
  

  #requestに登録する場合は、バリデーションが効かない
end

app/controllers/cabinets_controller.rb
class CabinetsController < ApplicationController #cabinetへの登録申請、承認等
  before_action :require_user_logged_in, only: [:index] #ApplicationControllerで定義したメソッド
  #before_action :correct_user, only: [:destroy]

  
  def index
    @msg = 'Cabinet data.'
    @cabinets = Cabinet.order(id: :asc).page(params[:page]).per(10)
  end

  def show
    @cabinet = Cabinet.find(params[:id])
  end

  def new #request仕掛画面で承認ボタン押下後、実行するメソッドでなきゃいけない。5.22
    @cabinet = Cabinet.new #cabinet登録への登録用5.24　パラメータを渡したいができない。。。
    @request = Request.new #requestへの登録画面を表示 cabinet new画面表示用5.24
  end

  def create
    @cabinet = Cabinet.new(cabinet_params) #cabinet_paramsを登録するため
    
    if @cabinet.save
      flash[:success] = '書庫への登録申請を受付けました。'
      redirect_to cabinets_url #redirect_toアクションはデータ保存後画面遷移
    else
      flash.now[:danger] = '書庫への登録申請に失敗しました。再度やり直してください。'
      render :new
    end
    
    @request = Request.new(cabinet_params) #request_paramsを登録するため
    @request.cabinet_id = @cabinet.id #request_id = cabinet_idと定義
    @request.user_id = current_user.id #requestのuser_id = 現在のidと定義
    @request.save
    
  end


  def edit
    @cabinet = Cabinet.find(params[:id])
  end

  def update #編集申請
    @cabinet = Cabinet.find(params[:id])
    if @cabinet.update_attributes(status: "編集申請中", manager_id:"NULL")
      flash[:success] = '編集申請を受け付けました'
      redirect_to cabinets_url
    else
      flash.now[:danger] = '編集申請に失敗しました'
      render :edit
    end
  end
  
  def update_delete #削除申請ボタン
    @cabinet = Cabinet.find(params[:id])
    if @cabinet.update_attributes(status: "削除申請中", manager_id:"NULL")
      flash[:success] = '削除申請を受付けました'
      redirect_to cabinets_url
    else
      flash.now[:danger] = '削除申請に失敗しました'
      render :edit
    end
  end
  
  def update_cancel #申請取り消しボタン
    @cabinet = Cabinet.find(params[:id])
    if @cabinet.update_attributes(status: "登録済" )
      flash[:success] = '申請を取り消しました'
      redirect_to cabinets_url
    else
      flash.now[:danger] = '申請取り消しに失敗しました'
      render :edit
    end
  end

  def update_accept #承認ボタン
    @cabinet = Cabinet.find(params[:id])
    if @cabinet.update_attributes(status: "登録済", manager_id:current_user.id) #statusを登録済に変更
      #@cabinet.request.update(status: "登録済") #request statusの更新は不要なので一旦コメントアウト
      flash[:success] = 'requestは承認されました'
      redirect_to cabinets_url
    else
      flash.now[:danger] = 'requestの承認に失敗しました'
      render action: :edit
    end
    #binding.pry #ブレイクポイント
  end



    
  def destroy #一つのデータを削除
    @cabinet = Cabinet.find(params[:id])
    @cabinet.destroy

    flash[:success] = '申請を取り消しました'
    redirect_to cabinets_url
  end
  
  def destroy_all #複数のデータを削除
    checked_data = params[:deletes].keys # ここでcheckされたデータを受け取っています。
    if @cabinets.destroy(checked_data)
      flash[:success] = '削除申請を受け付けました。'
      redirect_to cabinets_url
    else
      flash.now[:danger] = '削除申請に失敗しました。再度やり直してください。'
      render :new #cabinets/new.html.erbを表示するのみ（newアクションは実行しない）
    end
  end
end  



  private

  def cabinet_params #セキュリティ対策。newメソッドのフォーム入力データをフィルタリングする。HTTPリク攻撃防止
    params.require(:cabinet).permit(:file_no, :file_name, :expired_at, :placed_at, :user_id, :status, :manager_id)
    #Cabinetモデルを収集先に宣言。permit→その中で取得を許可する値。ユーザと管理者の取得情報の区別も可
  end
  
  def request_params #createに記載。使うために必要
    params.require(:request).permit(:file_no, :file_name, :expired_at, :placed_at, :user_id)
    #Requestモデルを収集先に宣言。permit→その中で取得を許可する値。ユーザと管理者の取得情報の区別も可
  end

app/views/cabinets/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: @cabinet, local: true) do |f| %>
      <% if @cabinet.errors.any? %>
        <div id="error_explanation" class="alert alert-warning">
          <ul class="mb-0">
            <% @cabinet.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group "> <%# form-inline form-control-plaintext で横並び%>
        <%= f.label :file_no, 'ファイルＮｏ' %> <%# f.label f.text_fieldでカラムを指定する %>
        <%= f.text_field :file_no, class: 'form-control', placeholder: "ex.YGM-01" %> <%# class以下がbootstrap %>
      </div>
      <div class="form-group "> 
        <%= f.label :file_name, 'ファイル名' %>
        <%= f.text_field :file_name, class: 'form-control', placeholder: "ex.2020fy NSC請求書" %>
      </div>
      

      <div class="form-group">
        <%= f.label :expired_at, '保管期限' %>
        <%= f.text_field :expired_at, class: 'form-control', placeholder: "ex.20270331" %>
      </div>

      <div class="form-group">
        <%= f.label :placed_at, '保管場所' %>
        <%= f.text_field :placed_at, class: 'form-control', placeholder: "ex.KI/SJ/1F/P2" %>
      </div>

      <div class="form-group">
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>



      <div class="form-group">
        <%= f.label :comment, 'コメント' %>
        <%= f.text_area :comment, class: 'form-control', placeholder: "ex.保管期限修正のため" %>
      </div>

      <%= f.submit '編集申請', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/cabinets/edit.html.erb
<h1>id: <%= @cabinet.id %> の編集ページ</h1>

<%= render "form", cabinet: @cabinet %>

app/views/cabinets/index.html.erb
<h1 class="display-3 text-primary">Cabinet</h1>

<h3><%= @msg %></h3>


<table class="table table-striped table-bordered text-center "> <%# table class="table" 基本のテーブルが作成される＋α %>

  <tr class="table-primary ">
    <th>No.</th><th>ファイルNo.</th><th>ファイル名</th><th>保管期限</th><th>保管場所</th><th>ステータス</th><th>起案者</th><th>承認者</th>
  </tr>

  <% @cabinets.each do |cabinet| %> <%# 一括データ取り出し %>
  <tr>

    <td><%= link_to cabinet.id, cabinet %></td>
    <td class="text-left"><%= cabinet.file_no %></td>
    <td class="text-left"><%= cabinet.file_name %></td>
    <td><%= cabinet.expired_at.strftime('%Y/%m/%d') %></td>
    <td><%= cabinet.placed_at %></td>
    <td><%= cabinet.status %></td> <%# 特定の文字色変更あとで。class="text-danger"　Cabiets.where.not(status: '登録済') %>
    <td><%= cabinet.user_id %></td>
    <td><%= cabinet.manager_id %></td>
  </tr>
  
  <% end %>
</table>


<%= paginate @cabinets %> <%# ページネイトができるようになる %>


<%# - @items.each do |item| %>
<%#  = check_box_tag'items[id][]', item.id %>

app/views/cabinets/new.html.erb
<div class="text-center"> <%# cabinetへの新規登録画面 %>
  <h1>Cabinetへの登録</h1>
</div>


<div class="row">
  <div class="col-sm-6 offset-sm-3 ">

    <%#= form_with(model: @request, local: true) do |f| %> <%# local: true⇒画面遷移可能 、@requestはrequest controllerのnewのインスタンス変数でPOSTreateをボタンのリンク先を指定createを %>
    <%= form_with(model: @cabinet, local: true) do |f| %>
    <%#= form_with(model: @request, url: requests_path,local: true) do |f| %>　<%# request controllerに飛ぶ %>
    <%#= form_with @request, url: {controller: 'requests', action: 'new' } do |form| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group "> <%# form-inline form-control-plaintext で横並び%>
        <%= f.label :file_no, 'ファイルＮｏ' %> <%# f.label f.text_fieldでカラムを指定する %>
        <%= f.text_field :file_no, class: 'form-control', placeholder: "ex.YGM-01" %> <%# class以下がbootstrap %>
      </div>

      <div class="form-group "> 
        <%= f.label :file_name, 'ファイル名' %>
        <%= f.text_field :file_name, class: 'form-control', placeholder: "ex.2020fy NSC請求書" %>
      </div>
      

      <div class="form-group">
        <%= f.label :expired_at, '保管期限' %>
        <%= f.date_field :expired_at, class: 'form-control' %>


      </div>

      <div class="form-group">
        <%= f.label :placed_at, '保管場所' %>
        <%= f.text_field :placed_at, class: 'form-control', placeholder: "ex.KI/SJ/1F/P2" %>
      </div>
      
      <div class="form-group">
        <%= f.label :comment, 'コメント' %>
        <%= f.text_area :comment, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.hidden_field :user_id, value: current_user.id %>
      </div>

      <div class="form-group">
        <%= f.hidden_field :status, value: "登録申請中" %>
      </div>
      
      <div class="form-group">
        <%= f.hidden_field :manager_id, value: 1 %>
      </div>
      
      <%= f.submit '登録申請', class: 'btn btn-primary ' %>  <%# f.submit⇒対応するモデルクラスが何も情報を持っていなければ自動的にcreateアクションへ、すでに情報を持っている場合はupdateアクションへ自動的に振り分けてくれる %>
      <%# btn-blockは横幅いっぱい%>
      
    <% end %>
  </div>
</div>

app/views/cabinets/show.html.erb
<%#= form_with(model: @cabinet, local: true) do |f| %>

<h1 class="display-5 text-dark">Cabinet(詳細)</h1>

<table class="table table-striped table table-bordered ">
  <tr>
    <th class="table-primary ">項目</th>
    <td class="table-primary ">内容</td>
  </tr>
  <tr>
    <th>登録No</th>
    <td><%= @cabinet.id %></td>
  </tr>
  <tr>
    <th>ファイルＮｏ</th>
    <td><%= @cabinet.file_no %></td>
  </tr>
  <tr>
    <th>ファイル名</th>
    <td><%= @cabinet.file_name %></td>
  </tr>
  <tr>
    <th>保管期限</th>
    <td><%= @cabinet.expired_at.strftime('%Y/%m/%d') %></td>
  </tr>
  <tr>
    <th>保管場所</th>
    <td><%= @cabinet.placed_at %></td>
  </tr>
    <tr>
    <th>ステータス</th>
    <td><%= @cabinet.status %></td>
  </tr>
  <tr>
    <th>起案者</th>
    <td><%= @cabinet.user_id %></td>
  </tr>
  <tr>
    <th>起案日</th>
    <td><%= @cabinet.created_at.strftime('%Y/%m/%d') %></td>
  </tr>
  <tr>
    <th>承認者</th>
    <td><%= @cabinet.manager_id %></td>
  </tr>

</table>

<%= link_to '一覧に戻る', cabinets_path, class: 'btn btn-light'  %>

<%= link_to '編集', edit_cabinet_path, class: 'btn btn-info' %>

<%= link_to '削除申請', update_delete_path(id: @cabinet.id), method: :patch, data: { confirm: '削除申請してよろしいですか？' }, class: 'btn btn-danger disabled: true ' %>

<%= link_to '申請取消し', update_cancel_path(id: @cabinet.id), method: :patch, data: { confirm: '申請を取り消しますか？' }, class: 'btn btn-success' %>
<%# end %>