config/routes.rb
Rails.application.routes.draw do

 namespace :admin do #admin/～を加える
  get 'signup', to: 'users#new' #user/newアクションのURLの最後はsignup

  resources :users, only: [:create]
  #get⇒users/index,show,new,edit (4つ)post⇒users/create (1つ)patch⇒users/update(1つ) put⇒users/update(１つ) delete⇒users/destroy(1つ)
 end  

  post 'cabinets', to: 'cabinets#create' #5.24追加
  post 'requests', to: 'requests#create' #5.24追加
  resources :requests #5.9追加 5.19変更

  root to: 'sessions#new' #root_to=最初の"/"でリンクする先を指定。
  
  get 'login', to: 'sessions#new' #session/newアクションのURLの最後はlogin
  post 'login', to: 'sessions#create' #session/createアクションのURLの最後はlogin
  delete 'logout', to: 'sessions#destroy' #session/destroyアクションのURLの最後はlogout
  

  delete :cabinets, to: 'cabinets#destroy_all' #5.6追加　一括削除
  patch 'update_delete', to: 'cabinets#update_delete' #6.6追加
  patch 'update_accept', to: 'cabinets#update_accept' #6.7追加
  patch 'update_cancel', to: 'cabinets#update_cancel' #6.13追加
  
  resources :cabinets  #, except: [:index]で除外可能
  #get⇒cabinets/index,show,new,edit (4つ)post⇒cabinets/create (1つ)patch⇒cabinets/update(1つ) put⇒cabinets/update(１つ) delete⇒cabinets/destroy(1つ)
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %> <%# モデルの中でエラーが一つでも存在するならtrueを返す %>
  <div id="error_explanation" class="alert alert-warning"> <%# 警告の黄色 %>
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %> <%# errors.full_message→エラーメッセの全取得 %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%# フォーム入力時のエラーメッセージ %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %> <%# オブジェクト.each.do |変数(ブロックパラメータ)キー, 〃値| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div> <%# .rbファイルを呼び出す %>
<% end %>

<%# ログイン可否時のフラッシュメッセージ %>

app/views/layouts/_navbar.html.erb
<header class="mb-5 pb-4"> <%# ナビバーの内余白下、外余白下を設定 %>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top"> <%# bootstrap適用 fixed-topナビ固定%>
    <a class="navbar-brand" href="/">Date Library</a> <%# 左上表記 %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"> <%# bootstrap適用 %>
      <span class="navbar-toggler-icon"></span> <%# bootstrap適用 %>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent"> <%# bootstrap適用 %>
      <ul class="navbar-nav"> <%# bootstrap適用 %>
        
        <%# ログイン後adminならsignupを表示、adminでないならsignup不要としたい%>
        
        <% if logged_in? %> <%# helperで定義している事が前提！ログインしている場合にlogoutを実装 %>  

        
        <% if current_user.admin? %> <%# .admin?は管理者ならtrueを返す %>
          <li class="nav-item"><%= link_to 'Signup', admin_signup_path, class: 'nav-link' %></li>  <%# cabinets_pathは/cabinet(index)に飛ぶ %>
          <li class="nav-item"><%= link_to 'Library', cabinets_path, class: 'nav-link' %></li>  <%# cabinets_pathは/cabinet(index)に飛ぶ %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right"> <%# プルダウン＋bootstrap適用 %>
              <li class="dropdown-item"><%= link_to 'cabinetへの登録', new_cabinet_path(current_user) %></li> <%# 仮設置 %>
              <li class="dropdown-item"><%= link_to '仕掛かり', requests_path(current_user) %></li> <%# user_path(10) # => 'users/10'に変換される %>
              <li class="dropdown-divider"></li> <%# current_user サインインしているユーザーを取得する %>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
        
          <li class="nav-item"><%= link_to 'Library', cabinets_path, class: 'nav-link' %></li>  <%# cabinets_pathは/cabinet(index)に飛ぶ %>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right"> <%# プルダウン＋bootstrap適用 %>
              <li class="dropdown-item"><%= link_to 'cabinetへの登録', new_cabinet_path(current_user) %></li> <%# user_path(10) # => 'users/10'に変換される %>
              <li class="dropdown-divider"></li> <%# current_user サインインしているユーザーを取得する %>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
          
        <% end %>
          
        <% else %> <%# falseの場合以下を実行 %>
          <%#<li class="nav-item">%><%#= link_to 'Signup', admin_signup_path, class: 'nav-link' %><%#</li>%> <%# ユーザはログイン機能のみ %>  
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Date Library</title> <%# タグ上の表示タイトル %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script> <%# bootstrapが適用される %>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %> <%# 上部ナビバー枠を設置。ex.render 'form' →_form.html.erbのようにパーシャルを呼ぶ %>
                                   <%# なぜ大元にrenderするのか？それはどのページに遷移しても同じバーを出したいため %>
    <div class="container"> <%# 格納庫。画面いっぱいに固定 %>
      <%= render 'layouts/flash_messages' %> <%# render 'ディレクトリ/パーシャルファイル' %>

      <%= yield %>
    </div>
  </body>
</html>